morphing_path: /nfs/scratch/fynu/fbury/UpgradeCalibrations/CMSSW_11_2_0_pre7/src/SimTracker/SiPhase2TimingCalibration/analysis/slurm/ScanUniform_2021-02-18_15-35-22/output/

hist_path: /nfs/scratch/fynu/fbury/UpgradeCalibrations/CMSSW_11_2_0_pre7/src/SimTracker/SiPhase2TimingCalibration/python/slurm/LowStat_2021-02-13_15-56-09/output/

evalList:
  - morphings: 
      - Morphing_mode_Latched_Threshold_3000p0_ThresholdSmearing_400p0_ToFSmearing_1p0.root
    hists: 
      - BXHistScan_N84_threshold3000_thresSmear400p0_ToFSmear1p0_harvested.root
    mode: Latched
    
