template_dir: &template_dir /home/ucl/cp3/fbury/scratch/UpgradeCalibrations/slurm/production/ttbar_noPu_2023-01-12_17-55-38/output/
subdir: ttbar_no_PU_scan_{mode}

parameters:
  N                 : Events
  threshold         : Threshold
  thresholdsmearing : Threshold Smearing
  tofsmearing       : ToF Smearing

scenarios:
  - test: 
      file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_0p0_harvested.root
      dir: *template_dir
      hists: !include hists.yml
    evaluators:
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_0p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_1p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_2p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_3p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_0p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_1p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_2p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_3p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml


  - test: 
      file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_3p0_harvested.root
      dir: *template_dir
      hists: !include hists.yml
    evaluators:
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_0p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_1p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_2p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: MeanEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_3p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_0p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_1p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_2p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml
      - method: LinearInterpolationEvaluator
        file: BXHistScan_subdet_ALL_N_100_pt_2p0_threshold_5000_thresholdsmearing_0p0_tofsmearing_3p0_harvested.root
        dir: *template_dir
        hists: !include hists.yml


       
